### ISSUE TITLE
gngeo-pi keyboard configuratio

### ISSUE THREAD

**Issue by lepit31** [ymartel06/GnGeo-Pi#1]
Hello
I am a new raspberry pi user and i try the last RetroPie

I can play with gngeo with metalslug 2 and 3 but only with the default key mapping
When i trie to change the key mapping with the ES-Config , i can save the new configuration file in : pi/.gngeo/gngeorc
(i check the file)
But when i start gngeo the new key mapping is not considered.
I tried to start with Emulstation or individually but no effect.

I miss somthing ?

**Comment by ghost** [comment]
Confirmed. I cannot make any settings take effect with the above file.

**Comment by ymartel06** [comment]
You should edit: ~/.gngeo/gngeorc

**Comment by ghost** [comment]
Yes, I believe that is what he is referencing.

My issue (now solved) appears to be that RetroPie has switched by default to PiFBA, despite most of the online documentation being written for gngeo.
