### ISSUE TITLE
Error and crash when loading ROM

### ISSUE THREAD

**Issue by nilsbyte** [ymartel06/GnGeo-Pi#2]
Hello, I am using the RetroPie-Setup script to install GnGeo-Pi.

At first try it worked without problems. The compiler built the binary, I placed the BIOS and I was able to run ROMs without any problem. Then I saw that Petrockblock had used the wrong parameters for compiling

`./configure --disable-i386asm --prefix="$rootdir/emulators/gngeo-pi-0.85/installdir"`

He changed it to the line in your README.md. I compiled the binary again with the updated script. When trying to open a ROM or changing a setting in the GnGeo-Pi menu, the program crashes with the following message:

`Catch a sigsegv effect none00ators/gngeo-pi-0.85/installdir/share/gngeo/gngeo_data.zip`

Petrockblock reverted the changes to the line above and I deleted the source, pulled it again and compiled, but now the error persists. Luckily I logged the console output of both attempts (both with the configure-line **without** `--host=arm-linux --target=arm-linux`). I found the only difference in the whole log is in this line:

**Working:**
`
gcc  -O2 -pipe -mfpu=vfp -march=armv6j -mfloat-abi=hard -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -O3 -Wall -Wno-unused -funroll-loops                     -ffast-math -g   -o gngeo pd4990a.o video.o profiler.o main.o list.o memory.o resfile.o timer.o frame_skip.o messages.o screen.o emu.o neocrypt.o sound.o unzip.o debug.o state.o conf.o transpack.o gnutil.o menu.o roms.o mame_layer.o neoboot.o event.o stb_image.o stb_zlib.o  generator68k_interf.o   mamez80_interf.o    effect/libeffect.a blitter/libblitter.a ym2610/libym2610.a generator68k/libgenerator68k.a mamez80/libmamez80.a  -lz -lm  -L/usr/lib/arm-linux-gnueabihf -lSDL
`

**Broken:**
`
gcc  -O2 -pipe -mfpu=vfp -march=armv6j -mfloat-abi=hard -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -O3 -Wall -Wno-unused -funroll-loops                     -ffast-math -g   -o gngeo pd4990a.o video.o profiler.o main.o list.o memory.o resfile.o timer.o frame_skip.o messages.o screen.o emu.o neocrypt.o sound.o unzip.o debug.o state.o conf.o transpack.o gnutil.o menu.o roms.o mame_layer.o neoboot.o event.o stb_image.o stb_zlib.o  generator68k_interf.o   mamez80_interf.o    effect/libeffect.a blitter/libblitter.a ym2610/libym2610.a generator68k/libgenerator68k.a mamez80/libmamez80.a  -lz -lm  -L/usr/lib -Wl,-rpath,/usr/lib -lSDL -lpthread
`

It's `-L/usr/lib/arm-linux-gnueabihf -lSDL`

I also found that the automake version used to create the Makefile in mamz80 differs. In the working try it was 1.11.3 and in the not working one 1.11.6. Maybe this is due to apt-get upgrade.

Can you see the problem?

**Comment by ymartel06** [comment]
Hi,

I think there is an issue inside some paths like /usr/lib should be usr/lib/arm-linux-gnueabihf.

Could you try to take my version from github and to install it?
wget -O gngeo-pi-0.85.tar.gz https://github.com/ymartel06/GnGeo-Pi/blob/master/releases/sources/gngeo-pi-0.85.tar.gz?raw=true
rm -rf /home/pi/RetroPie/emulators/gngeo-pi-0.85
tar xvfz gngeo-pi-0.85.tar.gz -C /home/pi/RetroPie/emulators/
pushd "/home/pi/RetroPie/emulators/gngeo-pi-0.85"
./configure --host=arm-linux --target=arm-linux --disable-i386asm --prefix="/home/pi/RetroPie/emulators/gngeo-pi-0.85/installdir"
make
make install
popd
mv /home/pi/RetroPie/emulators/gngeo-pi-0.85/installdir/bin/arm-linux-gngeo /home/pi/RetroPie/emulators/gngeo-pi-0.85/installdir/bin/gngeo
mv /home/pi/RetroPie/emulators/gngeo-pi-0.85/installdir/share/man/man1/arm-linux-gngeo.1 /home/pi/RetroPie/emulators/gngeo-pi-0.85/installdir/share/man/man1/gngeo.1

Thanks,

Yohann

**Comment by nilsbyte** [comment]
I already did that. The RetroPie-Setup script clones your repository:

https://github.com/petrockblog/RetroPie-Setup/blob/master/scriptmodules/emulators/gngeopi.sh#L10

I tried it with this - and the compressed one you just mentioned. Both result in a non-working binary as mentioned in my first post. It doesn't matter if i use `--host=arm-linux --target=arm-linux` or not when compiling.

**Edit:** Note that the paths in RetroPie have changed. Prefix is now 
`prefix="/opt/retropie/emulators/gngeo-pi-0.85/installdir"`

**Edit:** I have both binaries from the working try and the not working try if you need to inspect them.

**Comment by nilsbyte** [comment]
I tested with a fresh Raspbian again. I did:

apt-get upgrade 
apt-get install git dialog
cloned retropie_setup and started it to let it install the compilers
quit retropie_setup after that
apt-get install automake autoconf checkinstall
apt-get install libsdl1.2-dev

followed your instructions in README. changed paths to the new retropie paths. It compiled with the correct `-L/usr/lib/arm-linux-gnueabihf -lSDL`.

But it hangs when loading a ROM, maybe i forgot something? 

However, it looks like that **SDL 1.2.15 with dispmanx backend** (see: https://github.com/petrockblog/RetroPie-Setup/blob/master/scriptmodules/supplementary/sdl.sh) is causing all this.

Components in RetroPie-Setup are installed one after another from a customizable list. Some components before GnGeo-Pi already required `libsdl1.2-dev` which was installed then. 

This SDL 1.2.15... is installed after GnGeoPi which explains why it worked only the first time I compiled it. Second time **SDL 1.2.15 with dispmanx backend** was already installed and caused the wrong compile.

Can you maybe look whats causing the errors? It would be really helpful to know all the dependencies of GnGeo-Pi.

**Comment by nilsbyte** [comment]
Without installing dispmanx backend it compiles correctly and i can get into the main menu like before. When loading a ROM, gngeo-pi hangs and freezes the system wihout any message. Please, try for yourself, raspbian + apt-get upgrade + libsdl1.2-dev and compile it. It won't work. Can you fix that?

**Comment by ymartel06** [comment]
It looks ok, try retropie distribution.
