### ISSUE TITLE
JxHyy options don't seem to function with Hori Real Arcade Pro.4

### ISSUE THREAD

**Issue by Loxrie** [ymartel06/GnGeo-Pi#3]
It doesn't seem to matter how I configure pxcontrol in gngeorc the JxHyy option is not recognised.  I've compiled testjoystick.c on the pi against SDL (1, not 2).  The output is as follows:

```
Joystick 0: HORI CO.,LTD. Real Arcade Pro.4
       axes: 6
      balls: 0
       hats: 1
    buttons: 14
Watching joystick 0: (HORI CO.,LTD. Real Arcade Pro.4)
Joystick has 6 axes, 1 hats, 0 balls, and 14 buttons
Joystick 0 hat 0 value: 1
 up
Joystick 0 hat 0 value: 0
 centered
Joystick 0 hat 0 value: 4
 down
Joystick 0 hat 0 value: 0
 centered
Joystick 0 hat 0 value: 8
 left
Joystick 0 hat 0 value: 0
 centered
Joystick 0 hat 0 value: 2
 right
```

My current p1control line, which also uses four of the buttons as up down left right to help me test:

```
p1control A=J0B0,B=J0B3,C=J0B5,D=J0B4,START=J0B9,COIN=J0B12,UP=J0H01,DOWN=J0H04,LEFT=J0H08,RIGHT=J0H02,UP=J0B1,DOWN=J0B2,LEFT=J0B7,RIGHT=J0B6,MENU=J0B8
```

I've tried various iterations of J0H1, J0h1, J0H01 etc.  Looking at the source code didn't seem to provide any hints on what I was doing wrong.

**Comment by Loxrie** [comment]
Appears to be bug in code, way in which HAT mappings are made means eventual value of `map` changes depending on order in p1control.  Thus `if (player && map==GN_UP)` may never be true and thus hat inputs are not processed.  map value itself is not needed for that block of code:

```
diff --git a/gngeo/src/event.c b/gngeo/src/event.c
index 9ddb6f6..9b82672 100644
--- a/gngeo/src/event.c
+++ b/gngeo/src/event.c
@@ -287,9 +287,8 @@ int handle_event(void) {
                case SDL_JOYHATMOTION: /* Hat only support Joystick map */
                {
                        int player=jmap->jhat[event.jhat.which][event.jhat.hat].player;
-                       int map=jmap->jhat[event.jhat.which][event.jhat.hat].map;
                        int i;
-                       if (player && map==GN_UP) {
+                       if (player) {
                                player-=1;
                                for(i=GN_UP;i<=GN_RIGHT;i++)
                                        joy_state[player][i]=0;
```

**Comment by Loxrie** [comment]
Oh and correct setting I determined from source was that it's JxHy (e.g. Joystick no. Hat No.) directions are hard coded in the sense they come from SDL.  So the correct entries should read:

```
p1control A=J0B0,B=J0B3,C=J0B5,D=J0B4,START=J0B9,COIN=J0B12,UP=J0H0,DOWN=J0H0,LEFT=J0H0,RIGHT=J0H0,MENU=J0B8
```

this is just FYI anyone else reading it and wondering how to configure a joystick that shows up as a hat in sdl.

**Comment by ymartel06** [comment]
If I've got time, I would like to switch to SDL 2. Inputs will be processed differently.

**Comment by DebuRanger** [comment]
Hi,
Sorry about the comment.  I have a fight pad from hori as well as a PDP PS3 fight pad that don't seem to work with the D-PAD.  I have tried everything.  Is this still a known bug?
Is there a repo I can connect to that has a patch in it?

Thanks,
Debu
